name: eRouska

options:
  xcodeVersion: 1200
  groupSortPosition: top
  groupOrdering: 
    - pattern: eRouska
      order: [Interface, Services, Extensions, Resources, Supporting Files]

settings:
  IPHONEOS_DEPLOYMENT_TARGET: "13.5"
  MARKETING_VERSION: "2.3.0"
  CURRENT_PROJECT_VERSION: "4"

targets:
  eRouska Dev:
    templates:
      - App
    sources:
      - Generated
      - path: eRouska
        excludes:
          - Supporting Files/Firebase Prod/*
          - Supporting Files/Info.plist
          - Supporting Files/Info-Prod.plist
          - Configs
    entitlements:
      path: eRouska/Supporting Files/Entitlements/eRouska-Debug.entitlements
      properties:
        aps-environment: development
        com.apple.developer.associated-domains: [applinks:covid19cz.page.link]
        com.apple.security.app-sandbox: true
        com.apple.security.automation.apple-events: true
        com.apple.security.device.bluetooth: true
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.developer.exposure-notification: true
        com.apple.developer.exposure-notification-test: true
        com.apple.developer.exposure-notification-test-skip-file-verification: true
    configFiles:
      Debug: Configs/Dev-signing.xcconfig
      Release: Configs/Dev-signing.xcconfig
    settings:
      base:
        OTHER_LDFLAGS: -ObjC
        PRODUCT_BUNDLE_IDENTIFIER: 'cz.covid19cz.erouska.dev'
        INFOPLIST_FILE: eRouska/Supporting Files/Info.plist
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          CODE_SIGN_ENTITLEMENTS: eRouska/Supporting Files/Entitlements/eRouska-Debug.entitlements
        Release:
          CODE_SIGN_ENTITLEMENTS: eRouska/Supporting Files/Entitlements/eRouska-Relese.entitlements
          

  eRouska Prod:
    templates:
      - App
    sources:
      - Generated
      - path: eRouska
        excludes:
          - Supporting Files/Firebase Dev/*
          - Supporting Files/Info.plist
          - Supporting Files/Info-Prod.plist
          - Configs
    entitlements:
      path: eRouska/Supporting Files/Entitlements/eRouska-Relese.entitlements
      properties:
        aps-environment: development
        com.apple.developer.associated-domains: [applinks:covid19cz.page.link]
        com.apple.security.app-sandbox: true
        com.apple.security.automation.apple-events: true
        com.apple.security.device.bluetooth: true
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.developer.exposure-notification: true
    configFiles:
      Debug: Configs/Prod-signing.xcconfig
      Release: Configs/Prod-signing.xcconfig
    settings:
      base:
        OTHER_LDFLAGS: -ObjC
        PRODUCT_BUNDLE_IDENTIFIER: 'cz.covid19cz.erouska'
        INFOPLIST_FILE: eRouska/Supporting Files/Info-Prod.plist
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG PROD
          CODE_SIGN_ENTITLEMENTS: eRouska/Supporting Files/Entitlements/eRouska-Debug.entitlements
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: PROD
          CODE_SIGN_ENTITLEMENTS: eRouska/Supporting Files/Entitlements/eRouska-Relese.entitlements

targetTemplates:
  App:
    scheme:
      configVariants:
        # could stay empty to properly generate target scheme
    type: application
    platform: iOS
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        PRODUCT_MODULE_NAME: eRouska
        PRODUCT_NAME: eRouska
        CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
        DEVELOPMENT_TEAM: PDX4N72JDU
        CODE_SIGN_STYLE: Manual

    preBuildScripts:
      - path: Scripts/swiftlint.sh
        name: Swift Lint & Gen
        script: "swiftlint;swiftgen"

    postBuildScripts:
      - name: "Run Firebase Cashlytics"
        script: "${BUILD_DIR%Build/*}SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
        inputFiles: [
          "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}",
          "$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"
        ]
        runOnlyWhenInstalling: YES

    dependencies:
      - package: Alamofire
      - package: AlamofireImage
      - package: swift-crypto
        product: Crypto
      - package: DeviceKit
      - package: Reachability
      - package: RxDataSources
      - package: RxKeyboard
      - package: RxRealm
      - package: RxSwift
      - package: SwiftProtobuf
      - package: SwiftyMarkdown
      - package: Zip
      - package: Firebase
        product: FirebaseAnalytics 
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseFunctions
      - package: Firebase
        product: FirebaseRemoteConfig
      - package: JWTDecode
        product: JWTDecode

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.4.0
  AlamofireImage:
    url: https://github.com/Alamofire/AlamofireImage
    from: 4.1.0
  swift-crypto:
    url: https://github.com/apple/swift-crypto
    from: 1.1.5
  DeviceKit:
    url: https://github.com/devicekit/DeviceKit
    from: 4.3.0
  Reachability:
    url: https://github.com/ashleymills/Reachability.swift
    from: 5.1.0
  RxDataSources:
    url: https://github.com/RxSwiftCommunity/RxDataSources
    from: 5.0.0
  RxKeyboard:
    url: https://github.com/RxSwiftCommunity/RxKeyboard
    from: 2.0.0
  RxRealm:
    url: https://github.com/RxSwiftCommunity/RxRealm
    from: 5.0.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: 6.1.0
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf
    from: 1.15.0
  SwiftyMarkdown:
    url: https://github.com/augard/SwiftyMarkdown
    from: 1.2.5
  Zip:
    url: https://github.com/marmelroy/Zip
    from: 2.1.1
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 7.8.0
  JWTDecode:
    url: https://github.com/auth0/JWTDecode.swift
    from: 2.6.0
